### ISSUE TITLE
onChange function

### ISSUE THREAD

**Issue by tushariscoolster** [s-yadav/radialIndicator#1]
I am enabling interaction mode, i want to  get the current value of indication. How can i do that?

**Comment by s-yadav** [comment]
Thanks Tushar for pointing it out. Added it. Check the latest commit and doc http://www.ignitersworld.com/lab/radialIndicator.html#callbacks

Additionally you can also get indicator value using value method,
http://www.ignitersworld.com/lab/radialIndicator.html#methods
